### ISSUE TITLE
Next.js dev server stuck on "Compiling...' after version 3.3.1

### ISSUE THREAD

**Issue by Soberia** [0xa3k5/web3icons#25]
I can't get the dev server up on version 3.4.0 or later which has `fallback` support.
I have Next.js version `15.0.0-rc.0` and React `19.0.0-rc-2d2cc042-20240809` and run the dev server with TurboPack (`next dev --turbo`)

**Comment by 0xa3k5** [comment]
Thank you for reporting @Soberia I'm running a similar setup in [tokenicons.io](https://tokenicons.io) and it's running fine. Could you create a reproducable repo so I can see the issue?

**Comment by 0xa3k5** [comment]
also, do you see any errors? It's very interesting that the fallback prop has anything to do with it

**Comment by Soberia** [comment]
unfortunately, there are no errors. 

Steps to reproduce:

- run `npx create-next-app@rc --empty --turbo`
- run `npm install @web3icons/react@3.6.1`
- edit `src/app/page.tsx` to the following:

```typescript
"use client"

import {TokenIcon} from '@web3icons/react'

export default function Home() {
  return <TokenIcon symbol="btc" size="1rem" />
}
```

- run the dev server

```
> xxx@0.1.0 dev
> next dev --turbo

  ▲ Next.js 15.0.0-rc.0 (turbo)
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 2.8s
 ○ Compiling / ...
```

**Comment by 0xa3k5** [comment]
when I did that, it is working for me. I've realized the compiling takes a bit of time tho, I imagine it has something to do with internals of nextjs@15 which I can not optimize for at this time.

**Comment by Soberia** [comment]
It's weird, I tried on two different systems (Ubuntu 24.04 and WSL with node 20). both with the same result. server won't finish the compiling no matter how much time it takes.

I switched back to version 3.3.1, feel free to close the issue.

**Comment by 0xa3k5** [comment]
i will keep digging, will tag you if i can figure it out

**Comment by tanvir0604** [comment]
Same problem here. Its taking too much time to compile with this library.

**Comment by Soberia** [comment]
I think the issue is solved with version 3.10.0.
I tried with Next.js version `15.0.2-canary.10` and React version `19.0.0-rc-02c0e824-20241028`.

**Comment by Azleal** [comment]
hi @Soberia, so are you suggesting that both `NextConfig.experimental.optimizePackageImports` and `NextConfig.experimental.turbo.treeShaking` should be disabled to avoid this issue? I configed none of these, and I'm still having this problem.
